version: 1.0.0-{build}
image: Visual Studio 2017
init:
  - ps: $env:LABEL = "r" + $Env:APPVEYOR_BUILD_NUMBER.PadLeft(5, "0")
environment:
  COVERALLS_REPO_TOKEN:
    secure: iSIyjsIT4wQjKMwiLmW9v6LF1KWA9GDQR9vLlfYlg+R3RKeWhNWIgZmQ3g93mVRz
before_build:
  - ps: dotnet restore
build:
  parallel: true
  verbosity: minimal
test_script:
  - .\scripts\appveyor-tests.bat
after_test:
 - ps: iex ((Get-ChildItem ($env:USERPROFILE + '\.nuget\packages\OpenCover'))[0].FullName + '\tools\OpenCover.Console.exe' + ' -register:user -target:".\scripts\appveyor-tests.bat" -searchdirs:"$APPVEYOR_BUILD_FOLDER\test\DeveelDb.Core.Tests\bin\Release\netcoreapp1.1" -oldstyle -output:coverage.xml -skipautoprops -returntargetcode -filter:"+[DeveelDb*]* -[*Tests]* -[*Benchmark]*"')
 - ps: iex ((Get-ChildItem ($env:USERPROFILE + '\.nuget\packages\coveralls.io'))[0].FullName + '\tools\coveralls.net.exe' + ' --opencover coverage.xml')